### ISSUE TITLE
Is it possible to have multiple geofences?

### ISSUE THREAD

**Issue by blackbeario** [SarfarazAhmed008/geofence#1]
The examples show a single lat/lng. Is it possible to create an array of locations with this plugin?

**Comment by zumrywahid** [comment]
How can i cancel the existing geofence and re assign a new geofence ? I tried i am getting failure exception.

**Comment by SarfarazAhmed008** [comment]
> The examples show a single lat/lng. Is it possible to create an array of locations with this plugin?

Currently, its not supported for multiple locations.

**Comment by SarfarazAhmed008** [comment]
> How can i cancel the existing geofence and re assign a new geofence ? I tried i am getting failure exception.

To stop existing geofence service
`Geofence.stopGeofenceService();`
Also, you need to stop listening to stream subscription listener
For example (In my case): 
`geofenceEventStream.cancel();`

Re assigning is not supported yet. It will be available in future updates
